### ISSUE TITLE
How to read from SPI device?

### ISSUE THREAD

**Issue by mortenboye** [ardera/spidev.dart#1]
More usage example would be helpful, for instance how to read data from an SPI device.

**Comment by mortenboye** [comment]
I figured it out. Just read the rx buffer...

I'm reading from a MCP3008 ADC:
```
int channel = 0;
int cmd = 0x80 | ((channel & 0x07) << 4);
var txBuf = [0x00, 0x01, cmd, 0x00];
List<int> rxBuf = List<int>(4);
handle.transferSingleByteLists(txBuf: txBuf, rxBuf: rxBuf, transferProperties: SpiTransferProperties.defaultProperties).then((value) {
    var val = ((rxBuf[2] << 8) + rxBuf[3]) / 1024.0;
    print("received $rxBuf -> ${val}");
}).catchError((err) {
    print("SPI Error: $err");
});
```

**Comment by ardera** [comment]
Yeah exactly. Btw, you don't need to specify the `transferProperties` explicitly, it'll use the default properties when none are given. If you want, you can also use the same list as `txBuf` and `rxBuf`, it'll just overwrite the data in the list on receive.
